In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('datasets/MultipleRegression/50_Startups.csv')
x = dataset.iloc[:, :-1].values
print(x)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [3]:
y = dataset.iloc[:, 4].values
print(y)

[ 192261.83  191792.06  191050.39  182901.99  166187.94  156991.12
  156122.51  155752.6   152211.77  149759.96  146121.95  144259.4
  141585.52  134307.35  132602.65  129917.04  126992.93  125370.37
  124266.9   122776.86  118474.03  111313.02  110352.25  108733.99
  108552.04  107404.34  105733.54  105008.31  103282.38  101004.64
   99937.59   97483.56   97427.84   96778.92   96712.8    96479.51
   90708.19   89949.14   81229.06   81005.76   78239.91   77798.83
   71498.49   69758.98   65200.33   64926.08   49490.75   42559.73
   35673.41   14681.4 ]


In [4]:
#Encoding categorical variables
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder = LabelEncoder()
#creating the dummy varibales  
x[:,3] = label_encoder.fit_transform(x[:,3])
print(x)

[[165349.2 136897.8 471784.1 2]
 [162597.7 151377.59 443898.53 0]
 [153441.51 101145.55 407934.54 1]
 [144372.41 118671.85 383199.62 2]
 [142107.34 91391.77 366168.42 1]
 [131876.9 99814.71 362861.36 2]
 [134615.46 147198.87 127716.82 0]
 [130298.13 145530.06 323876.68 1]
 [120542.52 148718.95 311613.29 2]
 [123334.88 108679.17 304981.62 0]
 [101913.08 110594.11 229160.95 1]
 [100671.96 91790.61 249744.55 0]
 [93863.75 127320.38 249839.44 1]
 [91992.39 135495.07 252664.93 0]
 [119943.24 156547.42 256512.92 1]
 [114523.61 122616.84 261776.23 2]
 [78013.11 121597.55 264346.06 0]
 [94657.16 145077.58 282574.31 2]
 [91749.16 114175.79 294919.57 1]
 [86419.7 153514.11 0.0 2]
 [76253.86 113867.3 298664.47 0]
 [78389.47 153773.43 299737.29 2]
 [73994.56 122782.75 303319.26 1]
 [67532.53 105751.03 304768.73 1]
 [77044.01 99281.34 140574.81 2]
 [64664.71 139553.16 137962.62 0]
 [75328.87 144135.98 134050.07 1]
 [72107.6 127864.55 353183.81 2]
 [66051.52 182645.56 118148.2 1]
 [65605.48 153032.0

In [5]:
one_hot_encoder = OneHotEncoder(categorical_features=[3])
x = one_hot_encoder.fit_transform(x).toarray()
print(x)

[[  0.00000000e+00   0.00000000e+00   1.00000000e+00   1.65349200e+05
    1.36897800e+05   4.71784100e+05]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   1.62597700e+05
    1.51377590e+05   4.43898530e+05]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   1.53441510e+05
    1.01145550e+05   4.07934540e+05]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   1.44372410e+05
    1.18671850e+05   3.83199620e+05]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   1.42107340e+05
    9.13917700e+04   3.66168420e+05]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   1.31876900e+05
    9.98147100e+04   3.62861360e+05]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   1.34615460e+05
    1.47198870e+05   1.27716820e+05]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   1.30298130e+05
    1.45530060e+05   3.23876680e+05]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   1.20542520e+05
    1.48718950e+05   3.11613290e+05]
 [  1.00000000e+00   0.00000000e+00  

In [6]:
# Avoiding dummy variable trap
x = x[:, 1:]  # have to remove one dummy variable away, you don't need all three states

In [14]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# Fit multiple Linear Regression to the training set
from sklearn.linear_model import LinearRegression
# ignore this
import warnings
warnings.filterwarnings('ignore')

regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
# Predicting the Test set result
y_predict = regression.predict(X_test)

In [9]:
print("Real profits: ")
print(y_test)
print()
print("Predicted Profits by the model")
print(y_predict)

Real profits: 
[ 103282.38  144259.4   146121.95   77798.83  191050.39  105008.31
   81229.06   97483.56  110352.25  166187.94]

Predicted Profits by the model
[ 103015.20159795  132582.27760817  132447.73845176   71976.09851257
  178537.48221058  116161.24230165   67851.69209675   98791.73374686
  113969.43533013  167921.06569553]


In [10]:
# Building the optimal model using Backward Elimination
import statsmodels.formula.api as sm

In [11]:
x = np.append(arr=np.ones((50, 1)).astype(int), values=x, axis=1)
x_opt = x[:, [0, 1, 2, 3, 4, 5]]

In [12]:
# only contains independent variables that are highly significant variables that have impact on determining the
# to determine the profit
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Wed, 27 Dec 2017   Prob (F-statistic):           1.34e-27
Time:                        02:36:48   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.0

In [13]:
# removing independent variable that has highest P value which are columns 1,2,4,5
x_opt = x[:, [0, 3]]
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()
print(regressor_OLS.summary())
# This model can be used to forecast effects or impacts of changes.  
# That is, multiple linear regression analysis helps me to understand how much will the dependent variable change 
# when we change the independent variables. 

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Wed, 27 Dec 2017   Prob (F-statistic):           3.50e-32
Time:                        02:36:48   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.0